[project]
name = "pduut"
version = "0.1.0"
description = "PDUUT — PDF Data Unification and Understanding Tool. Extracts structured, page-wise data (text, images, tables, equations) from educational PDFs."
requires-python = ">=3.11"
dependencies = [
    "markdown>=3.8.2",
    "numpy>=2.3.2",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.1",
    "pillow>=11.3.0",
    "pymupdf>=1.26.3",
    "pytesseract>=0.3.13",
    "pyyaml>=6.0.2",
    "streamlit>=1.48.1",
]

authors = [
    { name = "Mohsin Raja" }
]
maintainers = [
    { name = "Mohsin Raja" }
]
